name: Auto.Tag

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/autotag-workflow.yaml
      - .github/workflows/slsa-container-generator.yaml
      - cmd/**
      - Dockerfile
      - go.mod
      - go.sum

jobs:
  tag:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Autotag the repository
      id: autotag
      uses: phish108/autotag-action@v1.1.64
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}

    - name: Trigger the slsa container generator workflow.
      run: |
        gh workflow run .github/workflows/slsa-container-generator.yaml --ref ${{ steps.autotag.outputs.new-tag }}
      env:
        GH_TOKEN: ${{ github.token }}